[package]
name = "demotask"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wit-bindgen-guest-rust = { path = "../../wit-bindgen/crates/guest-rust" }

[lib]
crate-type = ["cdylib"]